version: "3.8"

services:
  server_c:
    image: z34_server_image
    build: ./server_c
    container_name: z34_udp_server
    networks:
      - lab_network
    tty: true
    cap_add:
      - NET_ADMIN

  client_py:
    image: z34_client_image
    build: ./client_py
    container_name: z34_udp_client
    networks:
      - lab_network
    tty: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - server_c

networks:
  lab_network:
    external: true
    name: z34_network